<a href="https://colab.research.google.com/github/doo52oh/KaggleStudy/blob/master/Europen_Soccer/European_Soccer_Database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# European Soccer Database

##### 데이터 출처: https://www.kaggle.com/hugomathien/soccer

- database.sqlite 데이터베이스를 사용
 
- 데이터 베이스 내 총 7개의 Table 사용  
  * Country: 국가 정보  
  * League: 리그 정보   
  * Match: 경기 정보 (주 데이터셋)  
  * Player: 플레이어 정보  
  * Player_Attributes: 플레이어의 특성  
  * Team: 팀 정보  
  * Team_Attributes: 팀의 특성  

### Import Data

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sqlite3

import os

In [58]:
# os.environ을 이용하여 Kaggle API Username, Key 세팅
os.environ['KAGGLE_USERNAME'] = ''
os.environ['KAGGLE_KEY'] = ''

In [59]:
# aggle API를 이용하여 데이터셋 다운로드하기 (!kaggle ~)

!rm *.*
!kaggle datasets download -d hugomathien/soccer
!unzip '*.zip'

 83% 27.0M/32.7M [00:00<00:00, 33.0MB/s]
100% 32.7M/32.7M [00:00<00:00, 35.5MB/s]
Archive:  soccer.zip
  inflating: database.sqlite         


In [60]:
# sqlite3.connect()와 pd.read_sql_query()로 csv파일 읽어들이기
conn = sqlite3.connect('database.sqlite')

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
tables

type  ...                                                sql
0  table  ...             CREATE TABLE sqlite_sequence(name,seq)
1  table  ...  CREATE TABLE "Player_Attributes" (\n\t`id`\tIN...
2  table  ...  CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3  table  ...  CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4  table  ...  CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5  table  ...  CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6  table  ...  CREATE TABLE "Team" (\n\t`id`\tINTEGER PRIMARY...
7  table  ...  CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

[8 rows x 5 columns]

In [61]:

df_country = pd.read_sql_query('SELECT * FROM Country', conn)
df_league = pd.read_sql_query('SELECT * FROM League', conn)
df_match = pd.read_sql_query('SELECT * FROM Match', conn)
df_player = pd.read_sql_query('SELECT * FROM Player', conn)
df_player_att = pd.read_sql_query('SELECT * FROM Player_Attributes', conn)
df_team = pd.read_sql_query('SELECT * FROM Team', conn)
df_team_att = pd.read_sql_query('SELECT * FROM Team_Attributes', conn)

In [62]:
df_country.shape, df_league.shape, df_match.shape, df_player.shape, df_player_att.shape, df_team.shape, df_team_att.shape

((11, 2),
 (11, 3),
 (25979, 115),
 (11060, 7),
 (183978, 42),
 (299, 5),
 (1458, 25))

In [63]:
df_country.head()

id     name
0      1  Belgium
1   1729  England
2   4769   France
3   7809  Germany
4  10257    Italy

In [64]:
df_country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      11 non-null     int64 
 1   name    11 non-null     object
dtypes: int64(1), object(1)
memory usage: 304.0+ bytes


In [65]:
df_league.head()

id  country_id                    name
0      1           1  Belgium Jupiler League
1   1729        1729  England Premier League
2   4769        4769          France Ligue 1
3   7809        7809   Germany 1. Bundesliga
4  10257       10257           Italy Serie A

In [66]:
df_league.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          11 non-null     int64 
 1   country_id  11 non-null     int64 
 2   name        11 non-null     object
dtypes: int64(2), object(1)
memory usage: 392.0+ bytes


In [67]:
df_league['id'].unique()

array([    1,  1729,  4769,  7809, 10257, 13274, 15722, 17642, 19694,
       21518, 24558])

In [68]:
df_league['country_id'].unique()

array([    1,  1729,  4769,  7809, 10257, 13274, 15722, 17642, 19694,
       21518, 24558])

In [69]:
df_match.head()

id  country_id  league_id     season  stage  ...   GBD   GBA   BSH   BSD   BSA
0   1           1          1  2008/2009      1  ...  3.25  4.00  1.73  3.40  4.20
1   2           1          1  2008/2009      1  ...  3.25  3.75  1.91  3.25  3.60
2   3           1          1  2008/2009      1  ...  3.20  2.50  2.30  3.20  2.75
3   4           1          1  2008/2009      1  ...  3.75  5.50  1.44  3.75  6.50
4   5           1          1  2008/2009      1  ...  3.50  1.65  4.75  3.30  1.67

[5 rows x 115 columns]

In [70]:
df_match.season.unique()

array(['2008/2009', '2009/2010', '2010/2011', '2011/2012', '2012/2013',
       '2013/2014', '2014/2015', '2015/2016'], dtype=object)

In [71]:
df_match.stage.unique()

array([ 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  2, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29,  3, 30, 31, 32, 33, 34,  4,  5,  6,  7,  8,  9,
       35, 36, 37, 38])

In [72]:
df_match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB


In [73]:
for c in df_match.columns:
  print(c)

id
country_id
league_id
season
stage
date
match_api_id
home_team_api_id
away_team_api_id
home_team_goal
away_team_goal
home_player_X1
home_player_X2
home_player_X3
home_player_X4
home_player_X5
home_player_X6
home_player_X7
home_player_X8
home_player_X9
home_player_X10
home_player_X11
away_player_X1
away_player_X2
away_player_X3
away_player_X4
away_player_X5
away_player_X6
away_player_X7
away_player_X8
away_player_X9
away_player_X10
away_player_X11
home_player_Y1
home_player_Y2
home_player_Y3
home_player_Y4
home_player_Y5
home_player_Y6
home_player_Y7
home_player_Y8
home_player_Y9
home_player_Y10
home_player_Y11
away_player_Y1
away_player_Y2
away_player_Y3
away_player_Y4
away_player_Y5
away_player_Y6
away_player_Y7
away_player_Y8
away_player_Y9
away_player_Y10
away_player_Y11
home_player_1
home_player_2
home_player_3
home_player_4
home_player_5
home_player_6
home_player_7
home_player_8
home_player_9
home_player_10
home_player_11
away_player_1
away_player_2
away_player_3
away_player_4
a

In [74]:
for c, num in zip(df_match.columns, df_match.isna().sum()):
  print(c, num)

id 0
country_id 0
league_id 0
season 0
stage 0
date 0
match_api_id 0
home_team_api_id 0
away_team_api_id 0
home_team_goal 0
away_team_goal 0
home_player_X1 1821
home_player_X2 1821
home_player_X3 1832
home_player_X4 1832
home_player_X5 1832
home_player_X6 1832
home_player_X7 1832
home_player_X8 1832
home_player_X9 1832
home_player_X10 1832
home_player_X11 1832
away_player_X1 1832
away_player_X2 1832
away_player_X3 1832
away_player_X4 1832
away_player_X5 1832
away_player_X6 1832
away_player_X7 1832
away_player_X8 1832
away_player_X9 1833
away_player_X10 1833
away_player_X11 1839
home_player_Y1 1821
home_player_Y2 1821
home_player_Y3 1832
home_player_Y4 1832
home_player_Y5 1832
home_player_Y6 1832
home_player_Y7 1832
home_player_Y8 1832
home_player_Y9 1832
home_player_Y10 1832
home_player_Y11 1832
away_player_Y1 1832
away_player_Y2 1832
away_player_Y3 1832
away_player_Y4 1832
away_player_Y5 1832
away_player_Y6 1832
away_player_Y7 1832
away_player_Y8 1832
away_player_Y9 1833
away_player_Y

In [75]:
df_match.drop(df_match.columns[-38:], axis=1, inplace=True)

In [76]:
df_match.head()

id  country_id  league_id  ... away_player_9  away_player_10 away_player_11
0   1           1          1  ...           NaN             NaN            NaN
1   2           1          1  ...           NaN             NaN            NaN
2   3           1          1  ...           NaN             NaN            NaN
3   4           1          1  ...           NaN             NaN            NaN
4   5           1          1  ...           NaN             NaN            NaN

[5 rows x 77 columns]

In [77]:
df_player.head()

id  player_api_id         player_name  ...             birthday  height  weight
0   1         505942  Aaron Appindangoye  ...  1992-02-29 00:00:00  182.88     187
1   2         155782     Aaron Cresswell  ...  1989-12-15 00:00:00  170.18     146
2   3         162549         Aaron Doran  ...  1991-05-13 00:00:00  170.18     163
3   4          30572       Aaron Galindo  ...  1982-05-08 00:00:00  182.88     198
4   5          23780        Aaron Hughes  ...  1979-11-08 00:00:00  182.88     154

[5 rows x 7 columns]

In [78]:
df_player_att.head()

id  player_fifa_api_id  ...  gk_positioning gk_reflexes
0   1              218353  ...             8.0         8.0
1   2              218353  ...             8.0         8.0
2   3              218353  ...             8.0         8.0
3   4              218353  ...             7.0         7.0
4   5              218353  ...             7.0         7.0

[5 rows x 42 columns]

In [79]:
df_team.head()

id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [80]:
df_team_att.head()

id  team_fifa_api_id  ...  defenceTeamWidthClass defenceDefenderLineClass
0   1               434  ...                 Normal                    Cover
1   2               434  ...                 Normal                    Cover
2   3               434  ...                 Normal                    Cover
3   4                77  ...                   Wide                    Cover
4   5                77  ...                 Normal                    Cover

[5 rows x 25 columns]